# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-17 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.CreateModel(
            name='EasyGalleryPlugin',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_easy_gallery_easygalleryplugin', serialize=False, to='cms.CMSPlugin')),
                ('template', models.CharField(choices=[(b'default.html', b'default.html')], default=b'default.html', max_length=255, verbose_name='template')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_easy_gallery.Album')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangocms_easy_gallery.Album')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, to='filer.Image', verbose_name='Image')),
            ],
            options={
                'ordering': ('order',),
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
